### PR TITLE
Adding a WYSIWYG editor

### LINKED ISSUE #8: wysiwyg editor
was wondering if it would be difficult to incorporate the simple blog wysiwyg editor into the forum?

### PR DESCRIPTION
**Pull request by simon511000**
The editor is : [simplemde](https://simplemde.com)
**+ new config**
**+ fixed #8**
**- tinymce folder**

**Preview :**

### CODE REVIEW

**Comment by mitchellurgero** [comment]
Wow man, you are on FIRE. I might need to start donating to you. Good work!

**Comment by simon511000** [comment]
lol, you did 1000% of the job, I'm just making minor changes.
Bootforum is great, it took you so long to create it....
I love your way of coding

**Comment by mitchellurgero** [comment]
> I love your way of coding

Thank you! I try to make it as simple as I can so others can work on it easily :)

**Comment by simon511000** [comment]
Well it's successful :D

**Pull request merged**
