### PR TITLE
Fixed issues

### PR DESCRIPTION
**Pull request by mrl22**
I have removed multiple requires for config.php that are not needed and also stopped index.php from erroring when there are no posts.

### CODE REVIEW

**Comment by mitchellurgero** [comment]
I will review this pull request and might merge. Thanks for the help! Always nice to see someone else input on one of my projects :)

**Comment by mitchellurgero** [comment]
However, in config.php I see you put in DATAROOT. However that configuration variable should have a full path put in manually because I do not want the data accessible via the web server. htaccess was considered, however, not everyone uses apache or nginx.

**Comment by mrl22** [comment]
Sorry about the DATAROOT, I am using your forum as part of a much larger project so I am having to create branches. We have recently moved our projects from a server in our office to the cloud but we are having issues with git projects bring back code from other branches after switching.

**Comment by mitchellurgero** [comment]
Glad to see that someone else is finding a use for the software. :)

**Pull request merged**
